package com.uni.bailiff.controller.command;

public enum CommandName {
    GOTOHOMEPAGE, SEARCH, CLEAN, GOTOBAILIFFPAGE, GOTOOPERATIONPAGE, GOTOCLIENTPAGE,
    SORTBYCLIENT, SORTBYBAILIFF, SORTBYOPERATION, UPDATEORDER, UPDATEBAILIFF, UPDATEOPERATION,
    UPDATECLIENT, DELETEORDER, DELETEBAILIFF, DELETECLIENT, DELETEOPERATION, CREATENEWOPERATION,
    CREATENEWBAILIFF, CREATENEWORDER, CREATENEWCLIENT, GOTOUPDATEBAILIFFPAGE, GOTOUPDATECLIENTPAGE,
    GOTOUPDATEORDERPAGE, GOTOUPDATEOPERATIONPAGE
}
